# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/cache@v1

      # Copied from comments in primer check.yml:
      # renv cache makes install dependencies almost instaneous...if it works.
      # https://rstudio.github.io/renv/articles/ci.html
      # renv::consent(), line 37, seems to make it work. See https://github.com/r-lib/actions/issues/79

        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
             ${{ runner.os }}-renv-
      - name: Install dependencies
        run: |
          install.packages("renv")
          renv::consent(provided = TRUE)
          renv::restore()
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
